# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0003_user_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ManyToManyField(related_name='student_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
