# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20170813_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('online', models.IntegerField()),
                ('lessons', models.ManyToManyField(to='model.Lesson')),
            ],
        ),
    ]
