# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
    ]
