# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20170820_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplus',
            name='userid',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
