# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_remove_userplus_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplus',
            name='userid',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
