# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20170811_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
